### ISSUE TITLE
Sockethub down? (dead?)

### ISSUE THREAD

**Issue by abliss** [sockethub/sockethub#199]
http://demo.sockethub.org/examples/ ... server refused to connect
https://dogfeed.5apps.com/ ... doesn't seem to work at all
https://twitter.com/sockethub ... no posts for a year and a half
http://sockethub.org/news/ ... same

I'm having trouble figuring out whether this is a real thing? Or just a half-baked idea...? But it sounds kind of awesome...?!

**Comment by silverbucket** [comment]
Hi @abliss thanks for the nudge! I'm actually working on Sockethub right now in Indonesia (hackerbeach) :) We're working on making an open-source, unhosted, slack-clone (https://github.com/67P/hyperchannel) -- I've definitely be very bad about updating the news on sockethub.org, and was just thinking a few days ago I need to get back on that.

Timing wise, my server just went down a couple days ago due to a botched upgrade, and I haven't had the time to migrate everything over to a new server yet. And I don't twitter much so always forget about that. The server hosts both my own site, siverbucket.net, as well as sockethub.org and the demo (well actually the demo service has not been updated for the new version of sockethub yet - so it was offline anyway).

So while I am not being the best communicator, Sockethub is still very much going strong. I was unable to handle the workload of a full-time job as well as maintaining Sockethub + a large collection of related repositories and libraries while still making good web-apps all by myself. So I have discontinued dogfeed (for now at least) until I have more time to rewrite it and make it better. I actually want to un-deploy that dogfeed app from 5apps until it's ready to go again.

If you have any questions, or are interested in learning more and playing around and/or contributing with apps or helping out on a platform let me know.

**Comment by silverbucket** [comment]
Just a followup:
* sockethub.org back up
* demo.sockethub.org answering requests, but still not showing any demos. I took the reference to it off the website.
* dogfeed has been disabled as well, still plan to get this back on track
