### ISSUE TITLE
Platform failure affects different platform(s)

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub#248]
In https://github.com/67P/hyperchannel/pull/192#issuecomment-576357867 we found out that if e.g. the XMPP platform fails to connect to an XMPP server, the IRC platform will also disconnect immediately.

**Comment by silverbucket** [comment]
Yeah, I'm aware of this. It's actually not really a bug and more of a resource trade-off. In node, if an exception occurs you need to clear the memory of the process and restart it to ensure it's in a clean state, otherwise you get odd behavior, memory leaks, etc. For stateful connections this

**Comment by silverbucket** [comment]
Yeah, I'm aware of this. It's actually not really a bug and more of a resource trade-off. In node, if an exception occurs you need to clear the memory of the process and restart it to ensure it's in a clean state, otherwise you get odd behavior, memory leaks, etc.

**Comment by silverbucket** [comment]
Yeah, I'm aware of this. It's actually not really a bug and more of a resource trade-off. In node, if an exception occurs you need to clear the memory of the process and restart it to ensure it's in a clean state, otherwise you get odd behavior, memory leaks, etc. 

There are many different ways an exception can occur, but mainly I'm distinguishing between code I can and can't control, (Sockethub code or third party modules for platform implementations). 

There are three main options. The first is what Sockethub currently does, it launches 1 worker thread (separate node instance) per-user-session and uses any number of platform modules in that thread for that session. This has the side effect of needing to destory and restart the worker thread for that session when any of its platforms instances crash. 

The second way is to create a worker thread for each different platform. A single worker will handle all instance of IRC, for example. The side effect here is that you would need to kill all IRC sessions if one crashed. So instead of one user losing all of his stateful connections when one of them dies, all users would have all of their IRC connections closed when one instance in that worker pool dies.  

The third option is to do both, have a separate worker thread per-session per-platform. This is obviously the best behavior to the user, but the side effect would likely be major scaling issues. 

I went with the first as it seems the best temporary option, but am open to other ideas

**Comment by skddc** [comment]
I think a connection failure shouldn't cause an exception, because it is perfectly normal to be unable to connect to a server when e.g. the config is wrong. The only way to test if a server config works is by trying to connect. Also, a server could go down for maintenance or other reasons.

So I think the solution here would be to not have an exception, and simply return the connection error to the client so it can deal with it as normal behavior.

**Comment by silverbucket** [comment]
Without a fuller set of logs I can't really know for sure if we're talking about the same issue. @galfert or @skddc is it possible to include the logs from the first connection to both of them closing? In the parent ticket I just see the snippets of the close event but don't have too much context.

**Comment by skddc** [comment]
You can easily reproduce this yourself and look at all the logs as well as place debug statements etc.. Just add an XMPP space in Hyperchannel that has the wrong server port for example.
