### ISSUE TITLE
Problems with joining a channel and sending/receiving messages

### ISSUE THREAD

**Issue by galfert** [sockethub/sockethub#251]
As discussed in https://github.com/67P/hyperchannel/pull/192, there seems to be a problem with the connection and/or joining a channel that only happens sometimes.

I was able to connect to an XMPP server and then join a MUC room. I got the attendance list with all users in the channel, but I couldn't send or receive  any messages. I didn't see any errors in the Sockethub logs or any events that looked suspicious. But I also didn't see any events in the Sockethub log for either incoming or outgoing messages.

After I restarted Sockethub and connected to the same XMPP server and room, sending and receiving messages worked normally again.

Since there weren't any events for incoming or outgoing messages in the logs, I would assume that either the connection was broken or the join didn't work and my user wasn't actually a member of the channel.

Any ideas or pointers how to debug this?

**Comment by skddc** [comment]
As the repo context doesn't exist anymore, I think all platform issues need to be labelled with a platform label now.

**Comment by skddc** [comment]
I just tested this again with Hyperchannel master and the latest Sockethub release, and this is what happened:

* As described, no messages were sent out. However, the outgoing message showed without error in the Sockethub logs and was confirmed back to the client as sent.
* Also as described, no messages were coming in. Incoming messages also didn't show up in the Sockethub logs.
* Presence was announced correctly, and other clients could see the presence.
* Presence updates were also not coming in, when other users joined a room.

@silverbucket Let me know if you want to pair on this sometime during the next few days. I'd love to debug together with someone who knows the Sockethub code, so that I can start contributing on that side myself.

**Comment by galfert** [comment]
I think these issues have all been fixed with #258.
